image: Visual Studio 2022
configuration: Release
branches:
  only:
    - master

# build config
build_script:
  - dotnet build .\src

# tests config
test_script:
  - ps: dotnet test ((ls .\src\**\*.Tests.csproj | % FullName))

# pack config
after_test:
  - dotnet pack .\src

# artifacts config
artifacts:
  - path: '.\build\artifacts\*.nupkg'

# publish artifacts config
deploy:
  - provider: NuGet
    api_key:
      secure: +FtvpHdcRnhymyGhQT0j4fKmKzQiKsnnjmy4tTxzutvW3a307UgoSBJ7ASJLqmG3